title: Ekan Victor Attat
logo: Victor.png
description: Data Analytics expert. Close on a decade experience in accounting and finance
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
